backend:
  name: github
  repo: jaygiang/cloudinary-test

media_folder: content/assets
public_folder: ../assets

media_library:
  name: cloudinary
  config:
    cloud_name: du9yhowdr
    api_key: 937339823723728

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
